import type { Metadata } from "next"; // Importa el tipo TypeScript de Next.js para autocompletar y validar los metadatos de la página sin generar código JS
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; // Activa Tailwind en toda la APP
import Header from "@/components/Header"; // Importa el componente Header

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = { // Head HTML
  title: "Portafolio",
  description: "Generated by create next app", 
};

export default function RootLayout({ // Necesario para saber cómo renderizar la página
  children,
}: Readonly<{
  children: React.ReactNode; // Un React.ReactNode es simplemente cualquier cosa que sea HTML o un componente de React
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* 2. Colocamos el Header arriba del todo */}
        <Header /> 

        {/* 3. El contenido de tus páginas (como tu page.tsx) aparecerá justo aquí abajo */}
        {children} 
      </body>
    </html>
  );
}
